### ISSUE TITLE
Missing tests for send mail

### ISSUE THREAD

**Issue by astagi** [lotrekagency/djlotrek#2]
Use mock for testing

**Comment by shacharoo** [comment]
Hey @astagi , You can assign me to this if you'd like.

**Comment by astagi** [comment]
Sure @FarmerSez thank you :)

**Comment by shacharoo** [comment]
It seems that @abnerpc really wants a T shirt. Enjoy the tests nonetheless!

**Comment by astagi** [comment]
Sorry for that @FarmerSez :(
